// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/posts/[slug]/edit.tsx";
import * as $3 from "./routes/posts/[slug]/index.tsx";
import * as $4 from "./routes/posts/create.tsx";
import * as $5 from "./routes/trpc/[...path].ts";
import * as $$0 from "./islands/PostForm.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/posts/[slug]/edit.tsx": $2,
    "./routes/posts/[slug]/index.tsx": $3,
    "./routes/posts/create.tsx": $4,
    "./routes/trpc/[...path].ts": $5,
  },
  islands: {
    "./islands/PostForm.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
